
genRoe.exe: genRoe.cpp ../../DNDS_AutoDiff.hpp
	clang++ genRoe.cpp -o genRoe.exe -g -lopenblas -llapacke


genRoeTest.exe: genRoeTest.cpp ../../DNDS_AutoDiff.hpp
	g++ genRoeTest.cpp -o genRoeTest.exe -g -lopenblas -llapacke